name: CI

on:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - released
      - prereleased

jobs:

  mmwavelink-sys:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        default: true

    - name: Build mmwavelink-sys
      run: cargo build --release --manifest-path mmwavelink-sys/Cargo.toml

    - name: Test mmwavelink-sys
      run: cargo test --manifest-path mmwavelink-sys/Cargo.toml --tests  # skip doc tests (generated docs)

  
  mmwavelink:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        default: true

    - name: Build mmwavelink
      run: cargo build

    - name: Test mmwavelink  
      run: cargo test
